Observable collection Move behavior #355
punker76/gong-wpf-dragdrop pull request #362
Opened 2020-10-30 11:45 UTC by Mogikan

## What changed?

Instead of delete/insert move is called.

#355

2020-10-30 12:20 UTC, jizc requested changes
Here are my unsolicited suggestions 😉

2020-10-30 12:20 UTC, jizc commented on src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
> +                var sourceList = dropInfo.DragInfo.SourceCollection.TryGetList();
Should avoid adding whitespace to the end of lines.
```suggestion
                var sourceList = dropInfo.DragInfo.SourceCollection.TryGetList();
```

2020-10-30 12:20 UTC, jizc commented on src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
> +                    }
Should avoid adding whitespace to the end of lines.
```suggestion
                    }
```

2020-10-30 12:20 UTC, jizc commented on src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
> +
Unnecessary blank line
```suggestion
```

2020-10-30 12:20 UTC, jizc commented on src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
> +            //method = method.MakeGenericMethod(listItemType);
Should clean up comment out code
```suggestion
```

2020-10-30 12:20 UTC, jizc commented on src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
> +                throw new ArgumentException("ObservableCollection<T> was expected",nameof(list));
Should have a space between parameters.
```suggestion
                throw new ArgumentException("ObservableCollection<T> was expected", nameof(list));
```

2020-10-30 12:20 UTC, jizc commented on src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
> +using System.Reflection;
We don't need to add this `using` as both uses of `BindingFlags` below has the namespace included.
```suggestion
```

2020-10-30 12:20 UTC, jizc commented on src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
> +            return Equals(collection1, collection2) && IsObservableCollection(collection1);
Should use `ReferenceEquals` in this case.
```suggestion
            return ReferenceEquals(collection1, collection2) && IsObservableCollection(collection1);
```

2020-10-30 13:38 UTC, Mogikan reviewed
Thanks

2020-11-02 16:59 UTC, merged

2020-11-02 17:00 UTC, punker76 commented
@Mogikan your changes have been merged, thanks for your contribution 👍